# Generated by Django 2.1.5 on 2020-06-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='ads')),
                ('phone_number', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='ads')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazimazi.Category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazimazi.User'),
        ),
        migrations.AddField(
            model_name='ad',
            name='saved_ads',
            field=models.ManyToManyField(blank=True, related_name='saved_ads', to='bazimazi.User'),
        ),
        migrations.AddField(
            model_name='ad',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazimazi.State'),
        ),
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazimazi.Type'),
        ),
    ]
